version: '3.4'

services:
  todoapi:
    image: todoapi:dev
    build:
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "TodoAPI"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_todoapi$
    volumes:
      - C:\Users\sam\source\TestRepos\Todo-TestProject\src\todo\API:/app
      - C:\Users\sam\source\TestRepos\Todo-TestProject:/src
      - C:\Users\sam\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_todoapi$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_todoapi$ \"bin/Debug/netcoreapp3.0/TodoAPI.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true